// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufMessage.proto

package spring.cloud.stream.message.converter;

public final class ProtobufMessage {
  private ProtobufMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spring.cloud.stream.message.converter.DemoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 seqNo = 1;</code>
     */
    long getSeqNo();

    /**
     * <code>string content = 2;</code>
     */
    String getContent();
    /**
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    java.util.List<String>
        getReceiveTargetsList();
    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    int getReceiveTargetsCount();
    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    String getReceiveTargets(int index);
    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    com.google.protobuf.ByteString
        getReceiveTargetsBytes(int index);

    /**
     * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
     */
    DemoMessage.MessageType getType();
  }
  /**
   * Protobuf type {@code spring.cloud.stream.message.converter.DemoMessage}
   */
  public  static final class DemoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spring.cloud.stream.message.converter.DemoMessage)
      DemoMessageOrBuilder {
    // Use DemoMessage.newBuilder() to construct.
    private DemoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoMessage() {
      seqNo_ = 0L;
      content_ = "";
      receiveTargets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      type_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DemoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              seqNo_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                receiveTargets_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              receiveTargets_.add(s);
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          receiveTargets_ = receiveTargets_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufMessage.internal_static_spring_cloud_stream_message_converter_DemoMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufMessage.internal_static_spring_cloud_stream_message_converter_DemoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DemoMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code spring.cloud.stream.message.converter.DemoMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0),
      /**
       * <code>NOTIFICATION = 1;</code>
       */
      NOTIFICATION(1),
      /**
       * <code>WARNING = 2;</code>
       */
      WARNING(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>NOTIFICATION = 1;</code>
       */
      public static final int NOTIFICATION_VALUE = 1;
      /**
       * <code>WARNING = 2;</code>
       */
      public static final int WARNING_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return NOTIFICATION;
          case 2: return WARNING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DemoMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:spring.cloud.stream.message.converter.DemoMessage.MessageType)
    }

    private int bitField0_;
    public static final int SEQNO_FIELD_NUMBER = 1;
    private long seqNo_;
    /**
     * <code>int64 seqNo = 1;</code>
     */
    public long getSeqNo() {
      return seqNo_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile Object content_;
    /**
     * <code>string content = 2;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVETARGETS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList receiveTargets_;
    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getReceiveTargetsList() {
      return receiveTargets_;
    }
    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    public int getReceiveTargetsCount() {
      return receiveTargets_.size();
    }
    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    public String getReceiveTargets(int index) {
      return receiveTargets_.get(index);
    }
    /**
     * <code>repeated string receiveTargets = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveTargetsBytes(int index) {
      return receiveTargets_.getByteString(index);
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
     */
    public MessageType getType() {
      MessageType result = MessageType.valueOf(type_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seqNo_ != 0L) {
        output.writeInt64(1, seqNo_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      for (int i = 0; i < receiveTargets_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiveTargets_.getRaw(i));
      }
      if (type_ != MessageType.NORMAL.getNumber()) {
        output.writeEnum(4, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seqNo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seqNo_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < receiveTargets_.size(); i++) {
          dataSize += computeStringSizeNoTag(receiveTargets_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getReceiveTargetsList().size();
      }
      if (type_ != MessageType.NORMAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DemoMessage)) {
        return super.equals(obj);
      }
      DemoMessage other = (DemoMessage) obj;

      boolean result = true;
      result = result && (getSeqNo()
          == other.getSeqNo());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getReceiveTargetsList()
          .equals(other.getReceiveTargetsList());
      result = result && type_ == other.type_;
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQNO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeqNo());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getReceiveTargetsCount() > 0) {
        hash = (37 * hash) + RECEIVETARGETS_FIELD_NUMBER;
        hash = (53 * hash) + getReceiveTargetsList().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DemoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DemoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DemoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DemoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DemoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DemoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DemoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code spring.cloud.stream.message.converter.DemoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spring.cloud.stream.message.converter.DemoMessage)
        DemoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufMessage.internal_static_spring_cloud_stream_message_converter_DemoMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufMessage.internal_static_spring_cloud_stream_message_converter_DemoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DemoMessage.class, Builder.class);
      }

      // Construct using spring.cloud.stream.message.converter.ProtobufMessage.DemoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seqNo_ = 0L;

        content_ = "";

        receiveTargets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufMessage.internal_static_spring_cloud_stream_message_converter_DemoMessage_descriptor;
      }

      public DemoMessage getDefaultInstanceForType() {
        return DemoMessage.getDefaultInstance();
      }

      public DemoMessage build() {
        DemoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DemoMessage buildPartial() {
        DemoMessage result = new DemoMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.seqNo_ = seqNo_;
        result.content_ = content_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          receiveTargets_ = receiveTargets_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.receiveTargets_ = receiveTargets_;
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DemoMessage) {
          return mergeFrom((DemoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DemoMessage other) {
        if (other == DemoMessage.getDefaultInstance()) return this;
        if (other.getSeqNo() != 0L) {
          setSeqNo(other.getSeqNo());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.receiveTargets_.isEmpty()) {
          if (receiveTargets_.isEmpty()) {
            receiveTargets_ = other.receiveTargets_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureReceiveTargetsIsMutable();
            receiveTargets_.addAll(other.receiveTargets_);
          }
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DemoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DemoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long seqNo_ ;
      /**
       * <code>int64 seqNo = 1;</code>
       */
      public long getSeqNo() {
        return seqNo_;
      }
      /**
       * <code>int64 seqNo = 1;</code>
       */
      public Builder setSeqNo(long value) {

        seqNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 seqNo = 1;</code>
       */
      public Builder clearSeqNo() {

        seqNo_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 2;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList receiveTargets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReceiveTargetsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          receiveTargets_ = new com.google.protobuf.LazyStringArrayList(receiveTargets_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getReceiveTargetsList() {
        return receiveTargets_.getUnmodifiableView();
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public int getReceiveTargetsCount() {
        return receiveTargets_.size();
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public String getReceiveTargets(int index) {
        return receiveTargets_.get(index);
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveTargetsBytes(int index) {
        return receiveTargets_.getByteString(index);
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public Builder setReceiveTargets(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiveTargetsIsMutable();
        receiveTargets_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public Builder addReceiveTargets(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiveTargetsIsMutable();
        receiveTargets_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public Builder addAllReceiveTargets(
          Iterable<String> values) {
        ensureReceiveTargetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, receiveTargets_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public Builder clearReceiveTargets() {
        receiveTargets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string receiveTargets = 3;</code>
       */
      public Builder addReceiveTargetsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureReceiveTargetsIsMutable();
        receiveTargets_.add(value);
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
       */
      public MessageType getType() {
        MessageType result = MessageType.valueOf(type_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
       */
      public Builder setType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.spring.cloud.stream.message.converter.DemoMessage.MessageType type = 4;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:spring.cloud.stream.message.converter.DemoMessage)
    }

    // @@protoc_insertion_point(class_scope:spring.cloud.stream.message.converter.DemoMessage)
    private static final DemoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DemoMessage();
    }

    public static DemoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemoMessage>
        PARSER = new com.google.protobuf.AbstractParser<DemoMessage>() {
      public DemoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DemoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DemoMessage> getParserForType() {
      return PARSER;
    }

    public DemoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spring_cloud_stream_message_converter_DemoMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spring_cloud_stream_message_converter_DemoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025ProtobufMessage.proto\022%spring.cloud.st" +
      "ream.message.converter\"\315\001\n\013DemoMessage\022\r" +
      "\n\005seqNo\030\001 \001(\003\022\017\n\007content\030\002 \001(\t\022\026\n\016receiv" +
      "eTargets\030\003 \003(\t\022L\n\004type\030\004 \001(\0162>.spring.cl" +
      "oud.stream.message.converter.DemoMessage" +
      ".MessageType\"8\n\013MessageType\022\n\n\006NORMAL\020\000\022" +
      "\020\n\014NOTIFICATION\020\001\022\013\n\007WARNING\020\002B8\n%spring" +
      ".cloud.stream.message.converterB\017Protobu" +
      "fMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_spring_cloud_stream_message_converter_DemoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spring_cloud_stream_message_converter_DemoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spring_cloud_stream_message_converter_DemoMessage_descriptor,
        new String[] { "SeqNo", "Content", "ReceiveTargets", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
